name: AWS Credentials

on:
  workflow_call:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Assume AWS Role
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo $AWS_DEFAULT_REGION