name: AWS Credentials

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      AWS_ACCESS_KEY_ID:
        required: true
        type: string
      AWS_SECRET_ACCESS_KEY:
        required: true
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Assume AWS Role
        env:
          AWS_DEFAULT_REGION: ${{ inputs.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo $AWS_DEFAULT_REGION