name: AWS Credentials



on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
    inputs:
      PROJECT:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          echo "Secret: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "Project: ${{ inputs.PROJECT }}"
