name: AWS Credentials

env:
  AWS_REGION: "eu-west-2"
  AWS_ACCOUNT_ID_DEV: "654654324108"
  AWS_ACCOUNT_ID_PROD: "1234567890"
  ROLE_DEV: "DevAdminRole"
  ROLE_PROD: "ProdAdminRole"

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      STAGE:
        required: true
        type: string
      PROJECT:
        required: true
        type: string
      LAMBDA_NAME:
        required: true
        type: string
      BUILD_DIR:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:

      - name: Assume Role
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          output=$(aws sts assume-role --role-arn arn:aws:iam::${{ env.AWS_ACCOUNT_ID_DEV }}:role/${{ env.ROLE_DEV }} --role-session-name MySession)
          echo "AWS_ACCESS_KEY_ID=$(echo $output | jq -r .Credentials.AccessKeyId)" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $output | jq -r .Credentials.SecretAccessKey)" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $output | jq -r .Credentials.SessionToken)" >> $GITHUB_ENV


      - name: Build and Push Docker Image to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ env.AWS_REGION }}
          # Set AWS_ACCOUNT_ID and ROLE based on the STAGE input
          AWS_ACCOUNT_ID: ${{ inputs.STAGE == 'dev' && env.AWS_ACCOUNT_ID_DEV || env.AWS_ACCOUNT_ID_PROD }}
          ROLE: ${{ inputs.STAGE == 'dev' && env.ROLE_DEV || env.ROLE_PROD }}
          DOCKER_IMAGE: ${{ inputs.PROJECT }}-${{ inputs.LAMBDA_NAME }}-docker-image
          BUILD_DIR: ${{ inputs.BUILD_DIR }}
        run: |
          echo "Logging in to ECR..."
          echo "Using AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
          
          # Log in to ECR
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          
          # Check if the repository exists, create if it doesn't
          if ! aws ecr describe-repositories --repository-names ${{ inputs.PROJECT }} --region $AWS_REGION; then
            aws ecr create-repository --repository-name $DOCKER_IMAGE --region $AWS_REGION
          fi

          # Build the Docker image
          docker buildx build --platform linux/amd64 \
            --build-arg AWS_ACCESS_KEY_ID_ADMIN=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY_ADMIN=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --build-arg STAGE=${{ inputs.STAGE }} \
            -t $DOCKER_IMAGE $BUILD_DIR

          # Tag and push the Docker image
          docker tag $DOCKER_IMAGE:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:latest
