name: AWS Credentials

env:
  AWS_REGION: "eu-west-2"
  AWS_ACCOUNT_ID_DEV: "654654324108"
  AWS_ACCOUNT_ID_PROD: "905418370160"
  ROLE_DEV: "DevAdminRole"
  ROLE_PROD: "ProdAdminRole"

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      STAGE:
        required: true
        type: string
      PROJECT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Assume Role
        env:
          AWS_ACCOUNT_ID: ${{ inputs.STAGE == 'dev' && env.AWS_ACCOUNT_ID_DEV || env.AWS_ACCOUNT_ID_PROD }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ROLE: ${{ inputs.STAGE == 'dev' && env.ROLE_DEV || env.ROLE_PROD }}
        run: |
          output=$(aws sts assume-role --role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/$ROLE --role-session-name MySession)
          echo "AWS_ACCESS_KEY_ID=$(echo $output | jq -r .Credentials.AccessKeyId)" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $output | jq -r .Credentials.SecretAccessKey)" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $output | jq -r .Credentials.SessionToken)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.9.5"

      - name: Apply Terraform
        env:
          AWS_ACCOUNT_ID: ${{ inputs.STAGE == 'dev' && env.AWS_ACCOUNT_ID_DEV || env.AWS_ACCOUNT_ID_PROD }}
          AWS_ACCESS_KEY_ID_ADMIN: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY_ADMIN: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          STAGE: ${{ inputs.STAGE }}
          PROJECT: ${{ inputs.PROJECT }}
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
        run: |
          cd infra
          terraform fmt -check
          terraform init \
            -backend-config="bucket=terraform-state-${{ env.AWS_ACCOUNT_ID }}" \
            -backend-config="dynamodb_table=terraform-lock" \
            -backend-config="key=$PROJECT/terraform.tfstate" \
            -backend-config="region=$AWS_REGION" \
            -backend-config="encrypt=true"
          terraform plan -no-color \
            -var "aws_account_id=$AWS_ACCOUNT_ID" \
            -var "aws_region=$AWS_REGION" \
            -var "stage=$STAGE" \
            -var "project=$PROJECT" \
            -var "aws_access_key_id_admin=$AWS_ACCESS_KEY_ID_ADMIN" \
            -var "aws_secret_access_key_admin=$AWS_SECRET_ACCESS_KEY_ADMIN" \
            -var "version_number=$VERSION_NUMBER"
          terraform apply -auto-approve \
            -var "aws_account_id=$AWS_ACCOUNT_ID" \
            -var "aws_region=$AWS_REGION" \
            -var "stage=$STAGE" \
            -var "project=$PROJECT" \
            -var "aws_access_key_id_admin=$AWS_ACCESS_KEY_ID_ADMIN" \
            -var "aws_secret_access_key_admin=$AWS_SECRET_ACCESS_KEY_ADMIN" \
            -var "version_number=$VERSION_NUMBER"
